### ISSUE TITLE
Schema issue: PerPayout and PerFrequency should support nulls and max_amount should be optional

### ISSUE THREAD

**Issue by mbyrne00** [splitpayments/api-documentation#128]
**Bug Description**
https://github.com/zeptofs/api-documentation/blob/6fb88f423d85a8289a7543ea43aa019570900071/source/openapi3/split.yaml#L4005

### Per Payout
The `min_amount` and `max_amount` fields need the following to specify `null` is allowed

```yaml
    nullable: true
```

After update ...

```yaml
      properties:
        min_amount:
          type: integer
          nullable: true
          description: Minimum amount in cents a Payment Request can be in order to be auto-approved. Specify <code>null</code> for no limit.
          example: 0
        max_amount:
          type: integer
          nullable: true
          description: Maximum amount in cents a Payment Request can be in order to be auto-approved. Specify <code>null</code> for no limit.
          example: 10000
```

### Per Frequency

The `days` and `max_amount` fields need the following to specify `null` is allowed

```yaml
    nullable: true
```

After update ...

```yaml
      properties:
        days:
          type: integer
          nullable: true
          description: Amount of days to apply against the frequency. Specify <code>null</code> for no limit.
          example: 7
        max_amount:
          type: integer
          nullable: true
          description: >-
            Maximum amount in cents the total of all PRs can be for the duration
            of the frequency. Specify <code>null</code> for no limit.
          example: 1000000

```

Also ... `max_amount` is not a required field so that should be removed from `required` definitions. Remove it from 

```yaml
    PerFrequency:
      title: Per frequency terms
      required:
        - days
        - max_amount
```

Will keep raising these minor bugs as I notice them with our generated typescript types.  Sorry for noise, but should help to improve things for all.
